name: Notify Discord on New Issue

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send new issue to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_AVATAR: ${{ github.event.issue.user.avatar_url }}
          ISSUE_CREATED: ${{ github.event.issue.created_at }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Truncate and sanitize
          TRUNC_BODY=$(echo "$ISSUE_BODY" | head -c 200)
          [ -z "$TRUNC_BODY" ] && TRUNC_BODY="No description provided."

          # Create the payload using jq
          PAYLOAD=$(jq -n \
            --arg title "🆕 New Issue #$ISSUE_NUMBER: $ISSUE_TITLE" \
            --arg description "$TRUNC_BODY..." \
            --arg url "$ISSUE_URL" \
            --arg author "$ISSUE_AUTHOR" \
            --arg avatar "$ISSUE_AVATAR" \
            --arg repo "$REPO_NAME" \
            --arg created "$ISSUE_CREATED" \
            '{
              embeds: [{
                title: $title,
                description: $description,
                url: $url,
                color: 7506394,
                author: {
                  name: $author,
                  url: "https://github.com/" + $author,
                  icon_url: $avatar
                },
                footer: {
                  text: $repo
                },
                timestamp: $created
              }]
            }')

          # Send to Discord
          curl -X POST -H "Content-Type: application/json" \
               -d "$PAYLOAD" "$DISCORD_WEBHOOK"
