name: Notify Discord on New Issue

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send nicely formatted message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_AVATAR: ${{ github.event.issue.user.avatar_url }}
          ISSUE_DATE: ${{ github.event.issue.created_at }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Truncate the issue body to 200 chars, escape double quotes
          TRUNC_BODY=$(echo "$ISSUE_BODY" | head -c 200 | sed 's/"/\\"/g')
          if [ -z "$TRUNC_BODY" ]; then
            TRUNC_BODY="No description provided."
          fi

          # Send to Discord
          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"🆕 New Issue #$ISSUE_NUMBER: $ISSUE_TITLE\",
              \"description\": \"$TRUNC_BODY...\",
              \"url\": \"$ISSUE_URL\",
              \"color\": 7506394,
              \"author\": {
                \"name\": \"$ISSUE_AUTHOR\",
                \"url\": \"https://github.com/$ISSUE_AUTHOR\",
                \"icon_url\": \"$ISSUE_AVATAR\"
              },
              \"footer\": {
                \"text\": \"$REPO_NAME\"
              },
              \"timestamp\": \"$ISSUE_DATE\"
            }]
          }" \
          "$DISCORD_WEBHOOK"
